// Code generated by "stringer -type=CompoundType"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompoundTypeArray-38]
	_ = x[CompoundTypeFlatArray-95]
	_ = x[CompoundTypeTypedArray-64]
	_ = x[CompoundTypeAnyArray-126]
	_ = x[CompoundTypeTypedNonNullArray-94]
}

const (
	_CompoundType_name_0 = "CompoundTypeArray"
	_CompoundType_name_1 = "CompoundTypeTypedArray"
	_CompoundType_name_2 = "CompoundTypeTypedNonNullArrayCompoundTypeFlatArray"
	_CompoundType_name_3 = "CompoundTypeAnyArray"
)

var (
	_CompoundType_index_2 = [...]uint8{0, 29, 50}
)

func (i CompoundType) String() string {
	switch {
	case i == 38:
		return _CompoundType_name_0
	case i == 64:
		return _CompoundType_name_1
	case 94 <= i && i <= 95:
		i -= 94
		return _CompoundType_name_2[_CompoundType_index_2[i]:_CompoundType_index_2[i+1]]
	case i == 126:
		return _CompoundType_name_3
	default:
		return "CompoundType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
