// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataTypeUnknown-0]
	_ = x[DataTypeString-43]
	_ = x[DataTypeResponseCode-33]
	_ = x[DataTypeJson-36]
	_ = x[DataTypeSmallintSigned-45]
	_ = x[DataTypeSmallint-46]
	_ = x[DataTypeIntSigned-59]
	_ = x[DataTypeInt-58]
	_ = x[DataTypeFloat-37]
	_ = x[DataTypeBinaryString-63]
	_ = x[DataTypeArray-38]
	_ = x[DataTypeFlatArray-95]
	_ = x[DataTypeTypedArray-64]
	_ = x[DataTypeAnyArray-126]
	_ = x[DataTypeTypedNonNullArray-94]
}

const (
	_DataType_name_0 = "DataTypeUnknown"
	_DataType_name_1 = "DataTypeResponseCode"
	_DataType_name_2 = "DataTypeJsonDataTypeFloatDataTypeArray"
	_DataType_name_3 = "DataTypeString"
	_DataType_name_4 = "DataTypeSmallintSignedDataTypeSmallint"
	_DataType_name_5 = "DataTypeIntDataTypeIntSigned"
	_DataType_name_6 = "DataTypeBinaryStringDataTypeTypedArray"
	_DataType_name_7 = "DataTypeTypedNonNullArrayDataTypeFlatArray"
	_DataType_name_8 = "DataTypeAnyArray"
)

var (
	_DataType_index_2 = [...]uint8{0, 12, 25, 38}
	_DataType_index_4 = [...]uint8{0, 22, 38}
	_DataType_index_5 = [...]uint8{0, 11, 28}
	_DataType_index_6 = [...]uint8{0, 20, 38}
	_DataType_index_7 = [...]uint8{0, 25, 42}
)

func (i DataType) String() string {
	switch {
	case i == 0:
		return _DataType_name_0
	case i == 33:
		return _DataType_name_1
	case 36 <= i && i <= 38:
		i -= 36
		return _DataType_name_2[_DataType_index_2[i]:_DataType_index_2[i+1]]
	case i == 43:
		return _DataType_name_3
	case 45 <= i && i <= 46:
		i -= 45
		return _DataType_name_4[_DataType_index_4[i]:_DataType_index_4[i+1]]
	case 58 <= i && i <= 59:
		i -= 58
		return _DataType_name_5[_DataType_index_5[i]:_DataType_index_5[i+1]]
	case 63 <= i && i <= 64:
		i -= 63
		return _DataType_name_6[_DataType_index_6[i]:_DataType_index_6[i+1]]
	case 94 <= i && i <= 95:
		i -= 94
		return _DataType_name_7[_DataType_index_7[i]:_DataType_index_7[i+1]]
	case i == 126:
		return _DataType_name_8
	default:
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
