// Code generated by "stringer -type=ResponseCode"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RespOkay-0]
	_ = x[RespNil-1]
	_ = x[RespOverwriteError-2]
	_ = x[RespActionError-3]
	_ = x[RespPacketError-4]
	_ = x[RespServerError-5]
	_ = x[RespOtherError-6]
	_ = x[RespWrongtypeError-7]
	_ = x[RespUnknownDataType-8]
	_ = x[RespEncodingError-9]
	_ = x[RespBadCredentials-10]
	_ = x[RespAuthnRealmError-11]
}

const _ResponseCode_name = "OkayNilOverwriteErrorActionErrorPacketErrorServerErrorOtherErrorWrongtypeErrorUnknownDataTypeEncodingErrorBadCredentialsAuthnRealmError"

var _ResponseCode_index = [...]uint8{0, 4, 7, 21, 32, 43, 54, 64, 78, 93, 106, 120, 135}

func (i ResponseCode) String() string {
	if i < 0 || i >= ResponseCode(len(_ResponseCode_index)-1) {
		return "ResponseCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseCode_name[_ResponseCode_index[i]:_ResponseCode_index[i+1]]
}
